#!/usr/bin/env bash
set -e
# shellcheck source=./scripts/common
source "$(dirname "$0")/common"
source "$(dirname "$0")/utils"

if ! is_macos; then
    log_error 'This machine is not macOS!'
    exit 1
fi
[ -n "$SKIP_HOMEBREW" ] && exit
export SKIP_APT="true"

# Check prerequisites
log_step "PREREQ" "Checking prerequisites..."
check_internet || exit 1
check_xcode_tools

###########################################################
# Options
###########################################################
verbose=
for i in "$@"; do
    case "$i" in
    -s | --skip-apps)
        skip_apps=1
        shift
        ;;
    -v | --verbose)
        verbose=1
        shift
        ;;
    -ud | --update)
        update_homebrew=1
        shift
        ;;
    *) ;;
    esac
done

###########################################################
# Install Homebrew
###########################################################
arch_name="$(uname -m)"

if command_exists brew; then
    log_info "Homebrew is already installed."
else
    if [[ "${arch_name}" = "x86_64" && ! -f /usr/local/bin/brew ]]; then
        log 'Installing Homebrew...'
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/usr/local/bin:$PATH"
        log "Updating Homebrew..."
        brew update
    elif [[ "${arch_name}" = "arm64" && ! -f /opt/homebrew/bin/brew ]]; then
        log 'Installing Homebrew...'
        arch -arm64e /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/opt/homebrew/bin:$PATH"
        log "Updating Homebrew..."
        brew update
    fi
fi

if [ "$update_homebrew" ]; then
    log_step "UPDATE" "Updating Homebrew..."
    if ! brew update; then
        log_warn "Homebrew update failed, but continuing..."
    else
        log_success "Homebrew updated successfully"
    fi
fi

if [ ! "$skip_apps" ]; then
    log "Installing Apps and CLIs..."
    if is_file "${REPO_DIR}/homebrew/.config/homebrew/Brewfile"; then
        brew bundle install --file "${REPO_DIR}/homebrew/.config/homebrew/Brewfile" $([ -n "$verbose" ] && echo -v)
    elif is_file "${GHQ_ROOT_PATH}/github.com/${GITHUB_USER_NAME}/dotfiles/homebrew/.config/homebrew/Brewfile"; then
        brew bundle install --file "${GHQ_ROOT_PATH}/github.com/${GITHUB_USER_NAME}/dotfiles/homebrew/.config/homebrew/Brewfile" $([ -n "$verbose" ] && echo -v)
    else
        log "Brewfile not found. Please clone the dotfiles repository first:"
        log "  ghq get https://github.com/${GITHUB_USER_NAME}/dotfiles"
        exit 1
    fi
fi

true
